### 注意第一个member是在properties里配置的，第二个是在controller中写的，要分清
GET http://localhost:8000/member/member/count
Accept: application/json
token: 123

###

POST http://localhost:8000/member/member/register
Content-Type: application/json

{
  "mobile": 13995653856
}

###

POST http://localhost:8000/member/member/send_code
Content-Type: application/json

{
  "mobile": 13995653856
}

###


POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": 13995653850,
  "code": 8888
}


###
