### 注意第一个member是在properties里配置的，第二个是在controller中写的，要分清
GET http://localhost:8000/member/member/count
Accept: application/json

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=13487045829

###

POST http://localhost:8000/member/member/send_code
Content-Type: application/x-www-form-urlencoded

mobile=13487045828

###


POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded

mobile=13487045828&code=8888


###
