POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "memberId": "1",
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/query-list
Accept: application/json
token: {{token}}
#  信息保存在token所以不需要传递对应的memberId信息


###


POST http://localhost:8000/member/member/login
Content-Type: application/json



###
